<?php

/**
 * @file
 * Code for the Entity Validation Report module.
 */

/**
 * Implements hook_menu().
 */
function entity_validation_report_menu() {
  $return = array();

  $return['admin/reports/entity-validation-report'] = array(
    'title' => 'Entity Validation Report',
    'description' => 'Provides a report of all entities that do not pass validation.',
    'page callback' => 'entity_validation_report_page',
    'access callback' => TRUE,
    'file' => 'entity_validation_report.pages.inc',
    'type' => MENU_NORMAL_ITEM,
  );

  return $return;
}